spring:
 config:
  activate:
   on-profile: "qa"

build:
  version: "v1.0"
  
# ConfigurationProperties
contact:
  message: "Account API QA"
  details:
    name: "Divier Casas"
    email: "diviercasas26@gmail.com"
  phone-numbers:
    - "123"
    - "456"
  
