spring:
 application:
  name: "configserver"
 profiles:
  active: git
  #active: native
 cloud:
  config:
   server:
    git:
     uri: https://github.com/Divier/SpringConfig.git
     default-label: main
     timeout: 5
     clone-on-start: true #Spring cloud server clona el repositorio cuando arranca
     force-pull: true #Spring cloud server hace pull al repositorio para descartar alguna configurcion local
    #native:
     #search-locations: "classpath:/config" forma en que se pueden leer los archivos de configuracion
     #search-locations: "file:///C:\\Users\\hsrx4\\OneDrive\\Documentos\\SpringProjects\\spring-configs" #otra forma en que se pueden leer los archivos de configuracion
 rabbitmq:
  port: 5672
  host: "localhost"
  username: "guest"
  password: "guest"
server:
 port: 8071
#Activate actuator endpoints
management:
 endpoints:
  web:
   exposure:
    include: "*"
 health:
  livenessstate:
   enabled: true
  readinessstate:
   enabled: true
 endpoint:
  health:
   probes:
    enabled: true
